# Generated by Django 5.0.4 on 2024-04-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='link',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='status',
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='item_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='item_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Wish.itemdetails'),
        ),
    ]
