# Generated by Django 5.0.4 on 2024-05-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0002_itemdetails_remove_listitem_status_listitem_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='listitem',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
