# Generated by Django 5.0.4 on 2024-04-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0002_itemdetails_remove_listitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='product',
        ),
    ]
