# Generated by Django 5.0.4 on 2024-04-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0003_remove_list_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='item_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Wish.listitem'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='item_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='item_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
