# Generated by Django 5.0.4 on 2024-05-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0003_remove_listitem_item_id_listitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='status',
        ),
    ]
