# Generated by Django 5.0.4 on 2024-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0004_itemdetails_item_id_itemdetails_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='item_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
